#!/usr/bin/env python3
"""Generate the Bifrost pricing read-set from the Go datasheet structs.

Bifrost deserializes ``model_pricing.json`` into the ``datasheet.Entry`` struct
(``framework/modelcatalog/datasheet/types.go``), which embeds ``Options``. Every
field that struct does not declare is silently dropped on load. This script
parses those two structs and writes a snapshot of their JSON tags, so the merge
tool knows which pricing fields Bifrost actually reads.

The snapshot is checked in and must be regenerated whenever ``types.go`` gains a
cost field::

    python3 tools/gen_pricing_fields.py

Keeping this generated (rather than hand-maintained) is what stops the tool from
becoming a silent bottleneck that strips newly added Go fields.

Usage:
    python3 tools/gen_pricing_fields.py [--check] [--source PATH] [--out PATH]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Structs whose JSON tags make up the pricing read-set. ``Entry`` carries the
# capability/identity fields; ``Options`` carries every cost field.
READ_SET_STRUCTS = ("Entry", "Options")

DEFAULT_SOURCE = Path("framework/modelcatalog/datasheet/types.go")
DEFAULT_OUT = Path("datasheet_editor/pricing_fields.json")

# Go type -> coarse kind used to pick a GUI editor widget. Anything not listed
# (nested structs, aliases) is reported as "unknown" so the GUI falls back to a
# JSON text editor rather than guessing.
_SCALAR_KINDS = {
    "float64": "float",
    "float32": "float",
    "int": "int",
    "int64": "int",
    "int32": "int",
    "bool": "bool",
    "string": "string",
}


def _struct_body(lines: list[str], name: str) -> tuple[list[str], int] | None:
    """Return the lines of ``type <name> struct {`` up to its closing brace."""
    header = f"type {name} struct {{"
    for start, line in enumerate(lines):
        if line.startswith(header):
            body: list[str] = []
            for line in lines[start + 1 :]:
                if line == "}":
                    return body, start + 1
                body.append(line)
            return body, start + 1
    return None


_FIELD_RE = re.compile(
    r"^\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s+(?P<type>[^`\s]+(?:\s+[^\s`]+)?)\s+`(?P<tag>[^`]*)`"
)


def _go_kind(go_type: str) -> str:
    base = go_type.lstrip("*")
    return _SCALAR_KINDS.get(base, "unknown")


def parse_struct(lines: list[str], name: str) -> dict[str, dict[str, str]]:
    """Map each JSON tag on ``name`` to its Go field metadata."""
    found = _struct_body(lines, name)
    if found is None:
        raise SystemExit(f"error: struct {name!r} not found in source")
    body, lineno = found
    fields: dict[str, dict[str, str]] = {}
    for offset, line in enumerate(body):
        match = _FIELD_RE.match(line)
        if not match:
            continue
        tag_match = re.search(r'json:"([A-Za-z0-9_]+)', match.group("tag"))
        if not tag_match:
            continue
        tag = tag_match.group(1)
        if tag == "-":
            continue
        go_type = match.group("type").strip()
        fields[tag] = {
            "struct": name,
            "go_name": match.group("name"),
            "go_type": go_type,
            "kind": _go_kind(go_type),
            "line": str(lineno + offset + 1),
        }
    return fields


def parse_read_set(source: Path) -> dict[str, dict[str, str]]:
    """Parse every JSON tag on the read-set structs, keyed by tag name.

    Later structs win on collision; ``Options`` is parsed after ``Entry`` so its
    cost fields take precedence in the recorded metadata.
    """
    lines = source.read_text(encoding="utf-8").split("\n")
    merged: dict[str, dict[str, str]] = {}
    for struct in reversed(READ_SET_STRUCTS):
        merged.update(parse_struct(lines, struct))
    return dict(sorted(merged.items()))


def build(source: Path) -> dict[str, object]:
    fields = parse_read_set(source)
    try:
        rel = str(source.resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        rel = str(source)
    return {
        "_comment": (
            "Generated by tools/gen_pricing_fields.py from the Go datasheet "
            "structs. Do not edit by hand -- regenerate after changing types.go."
        ),
        "generated_from": rel,
        "structs": list(READ_SET_STRUCTS),
        "count": len(fields),
        "fields": fields,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE, help="path to types.go")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="snapshot output path")
    parser.add_argument("--check", action="store_true", help="verify the snapshot is current; do not write")
    args = parser.parse_args(argv)

    if not args.source.exists():
        print(f"error: source not found: {args.source}", file=sys.stderr)
        return 2

    payload = build(args.source)
    rendered = json.dumps(payload, indent=2, sort_keys=False) + "\n"

    if args.check:
        if not args.out.exists():
            print(f"error: snapshot missing: {args.out}", file=sys.stderr)
            return 1
        if args.out.read_text(encoding="utf-8") != rendered:
            print(
                f"error: {args.out} is stale; rerun tools/gen_pricing_fields.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {args.out} is current ({payload['count']} fields)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    kinds: dict[str, int] = {}
    for meta in payload["fields"].values():  # type: ignore[union-attr]
        kinds[meta["kind"]] = kinds.get(meta["kind"], 0) + 1
    print(f"wrote {args.out} ({payload['count']} fields: " + ", ".join(f"{k}={v}" for k, v in sorted(kinds.items())) + ")")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
