#!/command/with-contenv sh

while ! wget -q -O /dev/null http://127.0.0.1:$MINIO_PORT/minio/health/ready; do
    echo 'Bifrost is waiting for MinIO API to be ready...';
    sleep 1;
done;

exec /app/main -app-dir "${APP_DIR}" -port "${APP_PORT}" -host "${APP_HOST}" -log-level "${LOG_LEVEL}" -log-style "${LOG_STYLE}"