#!/command/with-contenv sh

while ! wget -q -O /dev/null http://127.0.0.1:${MINIO_PORT:-9000}/minio/health/ready; do
    echo 'Bifrost is waiting for MinIO API to be ready...';
    sleep 1;
done;

echo "Starting Bifrost..."
exec /app/main -app-dir "${APP_DIR:-/app/data}" -port "${APP_PORT:-8080}" -host "${APP_HOST:-0.0.0.0}" -log-level "${LOG_LEVEL:-info}" -log-style "${LOG_STYLE:-json}"